fastlane_version "1.81.0"

default_platform :android

platform :android do
	desc "Submit a new Build to Google Alpha Channel"
	lane :alpha do
	      gradle(task: "assembleRelease")
	      supply(track: "alpha", apk_paths: ["app/build/outputs/apk/release/app-release.apk"])
	end

	desc "Submit a new Build to Google Beta Channel"
	lane :beta do
              gradle(task: "assembleRelease")
	      supply(track: "beta", apk_paths: ["app/build/outputs/apk/release/app-release.apk"])
	end

	desc "Submit a new Build to Google Production Channel"
	lane :prod do
              gradle(task: "assembleRelease")
	      supply(apk_paths: ["app/build/outputs/apk/release/app-release.apk"])
	end
end
